### ISSUE TITLE
Software Engineer, Campus, Early Career

### ISSUE THREAD

**Issue by DonkeyBoy001** [haydenthai/New-Grad-2025#167]
### Link to Job Posting

https://www.google.com/about/careers/applications/jobs/results/103780715941765830-software-engineer/?src=Online/LinkedIn/linkedin_us&utm_source=linkedin&utm_medium=jobposting&utm_campaign=contractNew Role

### Company Name

Google

### Job Title

Software Engineer, Campus, Early Career

### Location

 Mountain View |  Atlanta

### Does this job offer sponsorship?

Offers Sponsorship

### Is this job currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

zhouzhenzhou111@outlook.com

**Comment by haydenthai** [comment]
Closing this issue as it;s for 2024 graduates
