### ISSUE TITLE
New Role: Vanguard Entry Level Applicaiton Engineer

### ISSUE THREAD

**Issue by haydenthai** [haydenthai/New-Grad-2025#182]
### Link to Job Posting

https://vanguard.wd5.myworkdayjobs.com/en-US/vanguard_external/job/Malvern-PA/Entry-Level-Application-Engineer---2025-Start-Date_162144-1

### Company Name

Vanguard

### Job Title

Entry Level Application Engineer - 2025 Start Date

### Location

Malvern, PA

### Does this job offer sponsorship?

Offers Sponsorship

### Is this job currently accepting applications?

Yes

**Comment by disha-baldawa** [comment]
Vanguard is not offering sponsorship for this position. It's in the job description

**Comment by haydenthai** [comment]
Oops, thanks for mentioning, wil lgo back and update
