### ISSUE TITLE
Moody's

### ISSUE THREAD

**Issue by Linlyo** [haydenthai/New-Grad-2025#273]
### Link to Job Posting

https://careers.moodys.com/ma-graduate-software-engineer/job/28403860

### Company Name

Moody's

### Job Title

MA Graduate-Software Engineer

### Location

Newark, California, 94560

### Does this job offer sponsorship?

Other

### Is this job currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

lyice.ll@gmail.com

**Comment by haydenthai** [comment]
Hey linlyo thanks so much for contributing. Unfortunately this role looks like it's for 2024 grads
